# Generated by Django 4.2.2 on 2024-06-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power", models.IntegerField()),
                ("rarity", models.CharField(max_length=50)),
                ("value", models.IntegerField()),
            ],
        ),
    ]